export const movies = [
  {id: '1', poster: '1.jpg'},
  {id: '2', poster: '2.jpg'},
  {id: '3', poster: '3.jpg'},
  {id: '4', poster: '4.jpg'},
  {id: '5', poster: '1.jpg'},
  {id: '6', poster: '2.jpg'},
  {id: '7', poster: '3.jpg'},
  {id: '8', poster: '4.jpg'},
  {id: '9', poster: '4.jpg'},
  {id: '10', poster: '4.jpg'},
  {id: '11', poster: '4.jpg'},
  {id: '12', poster: '4.jpg'},
];

export const sections = [
  {id: '1', title: 'Peliculas estrenos', movies},
  {id: '2', title: 'Recomendadas', movies},
  {id: '3', title: 'Dragon Ball - peliculas', movies},
];

export const categories = [
  {id: '1', name: 'Accion'},
  {id: '2', name: 'Accion Aventura'},
  {id: '3', name: 'Accion Drama'},
  {id: '4', name: 'Comedia'},
  {id: '5', name: 'Drama'},
  {id: '6', name: 'Animacion'},
  {id: '7', name: 'Animacion Aventura'},
  {id: '8', name: 'Aventura'},
  {id: '9', name: 'Aventura, Familia, Fantasia'},
  {id: '10', name: 'Belica'},
  {id: '11', name: 'Belico'},
  {id: '12', name: 'Belico Guerra'},
  {id: '13', name: 'Biografia'},
  {id: '14', name: 'Biografia'},
  {id: '15', name: 'Ciencia'},
  {id: '16', name: 'Ciencia Ficcion'},
  {id: '17', name: 'Deportes'},
  {id: '18', name: 'Documetal'},
  {id: '19', name: 'Familia'},
  {id: '20', name: 'Familiares'},
  {id: '21', name: 'Fantasia'},
  {id: '22', name: 'Guerra'},
  {id: '23', name: 'Historia'},
  {id: '24', name: 'Kids'},
  {id: '25', name: 'Misterio'},
  {id: '26', name: 'Musica'},
  {id: '27', name: 'News'},
  {id: '28', name: 'Pelicula TV'},
];
